export class MerchantWipComment {
    constructor(
        public errCode?: any,
        public errDesc?: any,
        public id?: number,
        public merchantWipId?: number,
        public storeName?: string,
        public tipeMerchant?: string,
        public jenisUsaha?: string,
        public alamat?: string,
        public kelurahan?: string,
        public kecamatan?: string,
        public provinsi?: string,
        public kabupatenKota?: string,
        public postalCode?: string,
        public longitude?: string,
        public lattitude?: string,
        public storePhoneNumber?: string,
        public lokasiBisnis?: string,
        public jenisLokasiBisnis?: string,
        public jamOperasional?: string,
        public merchantOutletId?: string,
        public merchantPan?: string,
        public referralCode?: string,
        public merchantCategoryCode?: string,
        public apikey?: string,
        public secretId?: string,
        public notes?: string,
        public merchantGroupId?: string,
        public ktpPath?: string,
        public selfiePath?: string,
        public merchantPhotoPath?: string,
        public merchantPhoto2Path?: string,
        public signPath?: string,
        public logoPath?: string,

    ) {}
}
