export class SettlementConfigWipComment {
    constructor(
        public errCode?: any,
        public errDesc?: any,
        public id?: number,
        public settlementConfigWipId?: number,
        public settlementConfig?: string,
        public noRekeningToko?: string,
        public namaBankTujuanSettlement?: string,
        public namaPemilikRekening?: string,
        public tipeRekening?: string,
        public reportSettlementConfig?: string,
        public settlementExecutionConfig?: string,
        public sendReportVia?: string,
        public sendReportUrl?: string,
        public processingConfiguration?: string,
        public processingFee?: string,
        public processingFeeValue?: string,
        public rentalEdcFee?: string,
        public mdr?: string,
        public mdrEmoneyOnUs?: string,
        public mdrEmoneyOffUs?: string,
        public mdrDebitOnUs?: string,
        public mdrDebitOffUs?: string,
        public mdrCreditOnUs?: string,
        public mdrCreditOffUs?: string,
        public otherFee?: string,
    ) {}
}
