export class MerchantOwner {
    constructor(
        public id?: number,
        public ownerTitle?: string,
        public ownerFirstName?: string,
        public ownerLastName?: string,
        public ownerAddress?: string,
        public ownerRt?: string,
        public ownerRw?: string,
        public ownerKelurahan?: string,
        public ownerKecamatan?: string,
        public ownerKabupaten?: string,
        public ownerKabupatenName?: string,
        public ownerProvinsi?: string,
        public ownerProvinsiName?: string,
        public ownerKodePos?: string,
        public ownerTipeID?: string,
        public ownerNoID?: string,
        public ownerTanggalExpiredID?: string,
        public ownerJenisKelamin?: string,
        public ownerNoTelp?: string,
        public ownerTelpLain?: string,
        public ownerPekerjaan?: string,
        public ownerEmail?: string,
        public ownerTempatLahir?: string,
        public ownerTanggalLahir?: string,
        public ownerNamaIbuKandung?: string,
        public errCode?: string,
        public errDesc?: string,
        public ownerNpwp?: string,
    ) { }
}
