import { MerchantGroup } from '../merchant-group/merchant-group.model';
import { MerchantOutlet } from './merchant-outlet.model';
import { MerchantOwner } from './merchant-owner.model';
import { MerchantSettlementConfig } from './merchant-settlement-config.model';

export class Merchant {
    constructor(
        public id?: number,
        public storeName?: string,
        public merchantGroup?: MerchantGroup,
        public settlementConfig?: MerchantSettlementConfig,
        public merchantOutlets?: MerchantOutlet,
        public owner?: MerchantOwner,
        public ktpPath?: string,
        public selfiePath?: string,
        public merchantPhotoPath?: string,
        public merchantPhoto2Path?: string,
        public signPath?: string,
        public logoPath?: string,
        public merchantType?: string,
        public jenisUsaha?: string,
        public jenisUsahaName?: string,
        public alamat?: string,
        public kelurahan?: string,
        public kecamatan?: string,
        public provinsi?: string,
        public provinsiName?: string,
        public kabupatenKota?: string,
        public kabupatenKotaName?: string,
        public postalCode?: string,
        public longitude?: string,
        public latitude?: string,
        public storePhoneNumber?: string,
        public lokasiBisnis?: string,
        public jenisLokasiBisnis?: string,
        public jamOperasional?: string,
        public hostStatus?: string,
        public referralCode?: string,
        public agentName?: string,
        public agentID?: string,
        public institutionID?: string,
        public merchantCategoryCode?: string,
        public merchantOutletID?: string,
        public merchantPan?: string,
        public apiKey?: string,
        public secretID?: string,
        public secretQuestion?: string,
        public secretQuestionAnswer?: string,
        public notes?: string,
        public reason?: string,
        public statusSuspense?: boolean,
        public errCode ?: string,
        public errDesc ?: string,
    ) {}
}
